export const Products={
    category:[
        {
            category:'Shirt',
            data:[
                {
                    name:'shirt-1',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt1.jpeg')
                },
                {
                    name:'shirt-2',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt2.jpeg')

                },
                {
                    name:'shirt-3',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt3.jpeg')

                },
                {
                    name:'shirt-4',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt4.jpeg')

                },
                {
                    name:'shirt-5',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt5.jpeg')

                },
                {
                    name:'shirt-6',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt6.jpeg')

                },
                {
                    name:'shirt-7',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt7.jpeg')

                },
                {
                    name:'shirt-8',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt8.jpeg')

                },
                {
                    name:'shirt-9',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt9.jpeg')

                },
                {
                    name:'shirt-10',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt10.jpeg')

                },
                {
                    name:'shirt-11',
                    price:300,
                    gender:'male',
                    image:require('eshop/src/images/shirt11.jpeg')

                },
                
            ],
        },
        {
            category:'t-shirt',
            data:[
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshit1.jpeg')
                },
                {
                    name:'tshirt-2',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt2.jpeg')
                },
                {
                    name:'tshirt-3',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shirt3.jpeg')
                },
                {
                    name:'tshirt-4',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt4.jpeg')
                },
                {
                    name:'tshirt-5',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt5.jpeg')
                },
                {
                    name:'tshirt-6',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt6.jpeg')
                },
                {
                    name:'tshirt-7',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt7.jpeg')
                },
                {
                    name:'tshirt-8',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt8.jpeg')
                },
                {
                    name:'tshirt-9',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt11.jpeg')
                },
                {
                    name:'tshirt-10',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/tshirt10.jpeg')
                },


            ]

        },
        {
            category:'shoes',
            data:[
                {
                    name:'shoes-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes1.jpeg')
                },
                {
                    name:'shoes-2',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes2.jpeg')
                },
                {
                    name:'shoes-3',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes3.jpeg')
                },
                {
                    name:'shoes-4',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes4.jpeg')
                },
                {
                    name:'shoes-5',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes5.jpeg')
                },
                {
                    name:'shoes-6',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes6.jpeg')
                },
                {
                    name:'shoes-7',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes7.jpeg')
                },
                {
                    name:'shoes-8',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes8.jpeg')
                },
                {
                    name:'shoes-9',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes9.jpeg')
                },
                {
                    name:'shoes-10',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/shoes10.jpeg')
                },


            ]

        },{
            category:'pant',
            data:[
                {
                    name:'pant-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant1.jpeg')
                },
                {
                    name:'pant-2',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant2.jpeg')
                },
                {
                    name:'pant-3',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant3.jpeg')
                },
                {
                    name:'pant-4',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant4.jpeg')
                },
                {
                    name:'pant-5',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant5.jpeg')
                },
                {
                    name:'pant-6',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant6.jpeg')
                },
                {
                    name:'pant-7',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant7.jpeg')
                },
                {
                    name:'pant-8',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant8.jpeg')
                },
                {
                    name:'tshirt-9',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant1.jpeg')
                },
                {
                    name:'pant-10',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/pant4.jpeg')
                },


            ]

        },{
            category:'top',
            data:[
                {
                    name:'Top-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top1.jpeg')
                },
                {
                    name:'Top-2',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top2.jpeg')
                },
                {
                    name:'Top-3',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top3.jpeg')
                },
                {
                    name:'Top-4',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top4.jpeg')
                },
                {
                    name:'Top-5',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top5.jpeg')
                },
                {
                    name:'Top-6',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top6.jpeg')
                },
                {
                    name:'Top-7',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top7.jpeg')
                },
                {
                    name:'Top-8',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top8.jpeg')
                },
                {
                    name:'Top-9',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top9.jpeg')
                },
                {
                    name:'Top-10',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/top10.jpeg')
                },


            ]

        },{
            category:'Lahnga',
            data:[
                {
                    name:'Lanhga-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga1.jpeg')
                },
                {
                    name:'Lanhga-2',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga2.jpeg')
                },
                {
                    name:'Lanhga-3',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga3.jpeg')
                },
                {
                    name:'Lanhga-4',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga4.jpeg')
                },
                {
                    name:'Lanhga-5',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga5.jpeg')
                },
                {
                    name:'Lanhga-6',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga6.jpeg')
                },
                {
                    name:'Lanhga-7',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga7.jpeg')
                },
                {
                    name:'Lanhga-8',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga8.jpeg')
                },
                {
                    name:'Lanhga-9',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lanhga9.jpeg')
                },
                {
                    name:'Lanhga-10',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/lahnga9.jpeg')
                },


            ]

        },{
            category:'t-shirt',
            data:[
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },
                {
                    name:'tshirt-1',
                    price:400,
                    gender:'male',
                    image:require('eshop/src/images/online-shopping.png')
                },


            ]

        },
    ],
};