export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const SHOW_THE_PRODUCT='SHOW_THE_PRODUCT'
export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST='REMOVE_FROM_WISHLIST';
export const SET_SELECTED_PRODUCT='SET_SELECTED_PRODUCT';
// export const ADD_TO_WISHLIS='ADD_TO_WISHLIS';

